# setup_uvworkon_alias.ps1 - Setup uvworkon alias for PowerShell
# This script creates a PowerShell alias for uvworkon command

param(
    [switch]$Force
)

Write-Host "uvworkon Alias Setup Script" -ForegroundColor Cyan
Write-Host "=============================" -ForegroundColor Cyan

# Get current script directory
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$UvworkonScript = Join-Path $ScriptDir "uvworkon.ps1"

# Check if uvworkon.ps1 exists
if (-not (Test-Path $UvworkonScript)) {
    Write-Host "Error: uvworkon.ps1 file not found at: $UvworkonScript" -ForegroundColor Red
    Write-Host "Please make sure this script is in the same directory as uvworkon.ps1" -ForegroundColor Red
    exit 1
}

Write-Host "[!] Found uvworkon.ps1 at: $UvworkonScript" -ForegroundColor Green

# Get PowerShell profile path
$ProfilePath = $PROFILE.CurrentUserAllHosts

Write-Host "[!] PowerShell profile path: $ProfilePath" -ForegroundColor Yellow
Write-Host ""

# Check if profile directory exists
$ProfileDir = Split-Path -Parent $ProfilePath
if (-not (Test-Path $ProfileDir)) {
    Write-Host "[!] Creating PowerShell profile directory..." -ForegroundColor Yellow
    New-Item -ItemType Directory -Path $ProfileDir -Force | Out-Null
}

# Check if profile already exists and contains uvworkon alias
$AliasExists = $false
if (Test-Path $ProfilePath) {
    $ProfileContent = Get-Content $ProfilePath -Raw
    if ($ProfileContent -match "uvworkon") {
        $AliasExists = $true
    }
}

if ($AliasExists -and -not $Force) {
    Write-Host "uvworkon alias already exists in PowerShell profile." -ForegroundColor Yellow
    Write-Host "Use -Force parameter to overwrite existing configuration." -ForegroundColor Yellow
    Write-Host ""
    exit 0
}

# Create the alias configuration
$AliasConfig = @"

#region uvworkon initialize
# Auto-generated by setup_uvworkon_alias.ps1
function uvworkon {
    param([string]`$EnvName)
    & "$UvworkonScript" `$EnvName
}
#endregion
"@

# Write to profile
Write-Host "Adding uvworkon alias to PowerShell profile..." -ForegroundColor Yellow

if ($AliasExists) {
    # Remove existing uvworkon configuration
    $ProfileContent = Get-Content $ProfilePath -Raw
    $ProfileContent = $ProfileContent -replace "(?s)#region uvworkon initialize.*?#endregion", ""
    Set-Content -Path $ProfilePath -Value $ProfileContent
}

# Append new configuration
Add-Content -Path $ProfilePath -Value $AliasConfig

Write-Host "Successfully added uvworkon alias to PowerShell profile!" -ForegroundColor Green
Write-Host ""
Write-Host "Usage:" -ForegroundColor Cyan
Write-Host "  uvworkon <env_name>     - Activate specified virtual environment" -ForegroundColor White
Write-Host "  uvworkon                - Show all available virtual environments" -ForegroundColor White
Write-Host ""
Write-Host "Note: You need to restart PowerShell or run the following command to load the alias:" -ForegroundColor Yellow
Write-Host "  . `$PROFILE" -ForegroundColor White
Write-Host ""
Write-Host "Or simply close and reopen PowerShell to use the uvworkon command." -ForegroundColor Yellow
